// Set the OPENAI_API_KEY environment variable before running.
// e.g., macOS/Linux: export OPENAI_API_KEY="sk-..."
//       PowerShell  : $env:OPENAI_API_KEY = "sk-..."

import OpenAI from "openai";
import { buildAIPlanPrompt, runQplan, setUserLanguage, validateQplanScript } from "../dist/index.js";

if (!process.env.OPENAI_API_KEY) {
  throw new Error("Set OPENAI_API_KEY before running this example.");
}

const client = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

const requirement = `
Read numbers from ./examples/nums.txt, calculate the total and average,
and print "High score" if the average is >= 5, otherwise print "Needs more study."
`;

// 0) Set user language (any string, e.g., "en", "ko", "ja")
setUserLanguage("ko");

// 1) buildAIPlanPrompt builds the LLM request automatically
const prompt = buildAIPlanPrompt(requirement);

console.log("============= buildAIPlanPrompt PROMPT ==================");
console.log(prompt);
console.log("============= buildAIPlanPrompt PROMPT end ==================");

// 2) Call OpenAI → receive raw QPlan script
// const model = process.env.OPENAI_MODEL ?? "gpt-4.1-mini"; // often fails
const model = process.env.OPENAI_MODEL ?? "gpt-4.1";

let aiScript = ""; // QPlan script generated by the LLM
const maxRetries = 3; // maximum retries
let lastErrorMessage = "";
let finalCtx = null;

for (let attempt = 1; attempt <= maxRetries; attempt++) {
  if(attempt > 1) {
    console.log(`=========== retrying (${attempt}) ===================`);
  }
  const completion = await client.chat.completions.create({
    model,
    temperature: 0.2,
    messages: [
      { role: "system", content: "You are a senior QPlan planner. Return only valid QPlan code." },
      { role: "user", content: attempt === 1 ? prompt : `${prompt}\n\nPrevious attempt failed because: ${lastErrorMessage}\nReturn a corrected QPlan script that fixes the issues above.` }
    ]
  });

  const raw = completion.choices[0]?.message?.content ?? "";
  // console.log(`raw (attempt ${attempt}):`, JSON.stringify(raw));

  aiScript = raw.trim();

  if (!aiScript) {
    lastErrorMessage = "The AI returned an empty script.";
    continue;
  }

  console.log("====== AI-generated QPlan ======");
  console.log(aiScript);

  const validation = validateQplanScript(aiScript);
  if (!validation.ok) {
    lastErrorMessage = `line ${validation.line ?? "?"}: ${validation.error}`;
    if (validation.issues?.length) {
      const issues = validation.issues.map(issue => `line ${issue.line}: ${issue.message}`).join(", ");
      lastErrorMessage += ` (details: ${issues})`;
    }
    console.error(`Invalid QPlan script (attempt ${attempt}).`, lastErrorMessage);

    if (attempt === maxRetries) {
      console.error("Exceeded maximum retries.");
      process.exit(1);
    }
    continue;
  }

  try {
    finalCtx = await runQplan(aiScript, {
      stepEvents: {
        async onStepStart(info) {
          console.log(`[STEP START] ${info.stepId}${info.desc ? ` (${info.desc})` : ""}`);
        },
        async onStepEnd(info) {
          console.log(`[STEP END] ${info.stepId}${info.desc ? ` (${info.desc})` : ""}`);
        }
      }
    });
    break;
  } catch (err) {
    lastErrorMessage = err instanceof Error ? err.message : String(err);
    console.error(`Execution failed (attempt ${attempt}):`, lastErrorMessage);
    if (attempt === maxRetries) {
      console.error("Exceeded maximum retries.");
      process.exit(1);
    }
  }
}

if (!finalCtx) {
  throw new Error("Execution did not complete successfully.");
}

console.log("====== Execution context ======");
console.log(finalCtx?.toJSON());
